theme = "kanagawa"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
g = { o = "jump_backward"}
"C-p" = "file_picker"
G = "goto_file_end"
"," = { d = ":q", "." = ":w"}
S = "hover"

[keys.insert]
"C-c" = "normal_mode"
