theme = "kanagawa"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
g = { b = "jump_backward"}
K = "hover"

[keys.insert]
j = { j = "normal_mode"}
