[default]
path = "/home/kkpagaev/Pictures/Wallpapers/"
duration = "30m"
sorting = "ascending"

[HDMI-A-1]
# path = "/home/danyspin97/Pictures/Wallpapers/github_octupus.png"
# path = "/home/kkpagaev/Pictures/Wallpapers/"
# path = "/home/kkpagaev/Pictures/Wallpapers/gold-darkness.jpg"
# path = "/home/kkpagaev/Pictures/Wallpapers/image_2023-08-07_02-16-06.png"
path = "/home/kkpagaev/Pictures/Wallpapers/gruv.jpeg"
# path = "/home/kkpagaev/Pictures/Wallpapers/image_2023-08-07_02-16-06.png"
# path = "/home/kkpagaev/Pictures/Wallpapers/kon.jpg"
# apply-shadow = true
#
[eDP-1]
# path = "/home/danyspin97/Pictures/Landscapes/"
# apply-shadow = true
# path = "/home/kkpagaev/Pictures/Wallpapers/"
path = "/home/kkpagaev/Pictures/Wallpapers/image_2023-08-07_02-16-06.png"
# path = "/home/kkpagaev/Pictures/Wallpapers/gold-darkness.jpg"
# path = "/home/kkpagaev/Pictures/Wallpapers/1215002.jpg"
# path = "/home/kkpagaev/Pictures/Wallpapers/Magical-Destroyers-op-screenshot.webp"
# path = "/home/kkpagaev/Pictures/Wallpapers/29.jpg"
# sorting = "descending"
